In [1]:
import pandas as pd
import numpy as np
import seaborn as sn

In [2]:
df=pd.read_csv("Train.csv")

In [3]:
df.drop("customer_id",axis=1,inplace=True)

In [4]:
Y=df[['primary_close_flag','final_close_flag']]

In [5]:
df.drop(["primary_close_flag","final_close_flag"],axis=1,inplace=True)

In [6]:
df.drop(['firstname','lastname'],inplace=True,axis=1)

In [7]:
df

,record_number,days_since_opened,days_since_confirmed,primary_term,final_term,days_till_primary_close,days_till_final_close,loans_credit_limit,loans_next_payment_summary,loans_outstanding_balance,...,encoded_payment_19,encoded_payment_20,encoded_payment_21,encoded_payment_22,encoded_payment_23,encoded_payment_24,encoded_loans_account_holder_type,encoded_loans_credit_status,encoded_loans_credit_type,encoded_loans_account_currency
0,7,10,8,12,10,13,5,11,2,3,...,1.0,2.0,0.0,1.0,3.0,4.0,1,3,4,1
1,5,15,6,7,6,9,1,5,6,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
2,1,15,17,8,5,9,1,6,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
3,11,7,2,11,13,14,8,14,3,5,...,3.0,4.0,3.0,3.0,3.0,4.0,1,2,4,1
4,12,14,9,8,11,6,13,5,6,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106669,19,1,5,8,11,2,6,18,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,5,1
1106670,10,5,8,4,3,5,7,18,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,5,1
1106671,3,8,7,13,0,4,9,3,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
1106672,4,10,4,16,9,6,13,3,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
1106673,12,1,10,10,13,10,8,8,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,2,3,1

In [8]:
data_types = df.dtypes
print(data_types)

record_number                           int64
days_since_opened                       int64
days_since_confirmed                    int64
primary_term                            int64
final_term                              int64
days_till_primary_close                 int64
days_till_final_close                   int64
loans_credit_limit                      int64
loans_next_payment_summary              int64
loans_outstanding_balance               int64
loans_max_overdue_amount                int64
loans_credit_cost_rate                  int64
loans_within_5_days                     int64
loans_within_5_to_30_days               int64
loans_within_30_to_60_days              int64
loans_within_60_to_90_days              int64
loans_over_90_days                      int64
is_zero_loans_within_5_days            object
is_zero_loans_within_5_to_30_days      object
is_zero_loans_within_30_to_60_days     object
is_zero_loans_within_60_to_90_days     object
is_zero_loans_over_90_days             object
utilization                             int64
over_limit_count                        int64
max_over_limit_count                    int64
is_zero_utilization                    object
is_zero_over_limit_count               object
is_zero_max_over_limit_count           object
encoded_payment_0                     float64
encoded_payment_1                     float64
encoded_payment_2                     float64
encoded_payment_3                     float64
encoded_payment_4                     float64
encoded_payment_5                     float64
encoded_payment_6                     float64
encoded_payment_7                     float64
encoded_payment_8                     float64
encoded_payment_9                     float64
encoded_payment_10                    float64
encoded_payment_11                    float64
encoded_payment_12                    float64
encoded_payment_13                    float64
encoded_payment_14                    float64
encoded_payment_15                    float64
encoded_payment_16                    float64
encoded_payment_17                    float64
encoded_payment_18                    float64
encoded_payment_19                    float64
encoded_payment_20                    float64
encoded_payment_21                    float64
encoded_payment_22                    float64
encoded_payment_23                    float64
encoded_payment_24                    float64
encoded_loans_account_holder_type       int64
encoded_loans_credit_status             int64
encoded_loans_credit_type               int64
encoded_loans_account_currency          int64
dtype: object

In [9]:
categorical_columns = ["is_zero_loans_within_5_days", "is_zero_loans_within_5_to_30_days", "is_zero_loans_within_30_to_60_days", "is_zero_loans_within_60_to_90_days", "is_zero_loans_over_90_days"]

for col in categorical_columns:
    unique_values = df[col].unique()
    print(f"Unique values in '{col}': {unique_values}")

Unique values in 'is_zero_loans_within_5_days': ['Yes' 'No']
Unique values in 'is_zero_loans_within_5_to_30_days': ['No' 'Yes']
Unique values in 'is_zero_loans_within_30_to_60_days': ['Yes' 'No']
Unique values in 'is_zero_loans_within_60_to_90_days': ['Yes' 'No']
Unique values in 'is_zero_loans_over_90_days': ['Yes' 'No']

In [10]:
from sklearn.preprocessing import LabelEncoder
columns_to_convert = ['is_zero_loans_within_5_days', 'is_zero_loans_within_5_to_30_days', 'is_zero_loans_within_30_to_60_days','is_zero_loans_within_60_to_90_days','is_zero_loans_over_90_days','is_zero_utilization','is_zero_over_limit_count','is_zero_max_over_limit_count']  
label_encoder = LabelEncoder()

for column in columns_to_convert:
    df[column] = label_encoder.fit_transform(df[column])

In [11]:
df

,record_number,days_since_opened,days_since_confirmed,primary_term,final_term,days_till_primary_close,days_till_final_close,loans_credit_limit,loans_next_payment_summary,loans_outstanding_balance,...,encoded_payment_19,encoded_payment_20,encoded_payment_21,encoded_payment_22,encoded_payment_23,encoded_payment_24,encoded_loans_account_holder_type,encoded_loans_credit_status,encoded_loans_credit_type,encoded_loans_account_currency
0,7,10,8,12,10,13,5,11,2,3,...,1.0,2.0,0.0,1.0,3.0,4.0,1,3,4,1
1,5,15,6,7,6,9,1,5,6,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
2,1,15,17,8,5,9,1,6,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
3,11,7,2,11,13,14,8,14,3,5,...,3.0,4.0,3.0,3.0,3.0,4.0,1,2,4,1
4,12,14,9,8,11,6,13,5,6,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106669,19,1,5,8,11,2,6,18,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,5,1
1106670,10,5,8,4,3,5,7,18,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,5,1
1106671,3,8,7,13,0,4,9,3,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
1106672,4,10,4,16,9,6,13,3,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
1106673,12,1,10,10,13,10,8,8,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,2,3,1

In [12]:


# Iterate through columns and fill null values with the mode
for column in df.columns:
    mode_value = df[column].mode().values[0]  # Find the mode value
    df[column].fillna(mode_value, inplace=True)  # Fill null values with the mode

In [13]:
df.isnull().sum()

record_number                         0
days_since_opened                     0
days_since_confirmed                  0
primary_term                          0
final_term                            0
days_till_primary_close               0
days_till_final_close                 0
loans_credit_limit                    0
loans_next_payment_summary            0
loans_outstanding_balance             0
loans_max_overdue_amount              0
loans_credit_cost_rate                0
loans_within_5_days                   0
loans_within_5_to_30_days             0
loans_within_30_to_60_days            0
loans_within_60_to_90_days            0
loans_over_90_days                    0
is_zero_loans_within_5_days           0
is_zero_loans_within_5_to_30_days     0
is_zero_loans_within_30_to_60_days    0
is_zero_loans_within_60_to_90_days    0
is_zero_loans_over_90_days            0
utilization                           0
over_limit_count                      0
max_over_limit_count                  0
is_zero_utilization                   0
is_zero_over_limit_count              0
is_zero_max_over_limit_count          0
encoded_payment_0                     0
encoded_payment_1                     0
encoded_payment_2                     0
encoded_payment_3                     0
encoded_payment_4                     0
encoded_payment_5                     0
encoded_payment_6                     0
encoded_payment_7                     0
encoded_payment_8                     0
encoded_payment_9                     0
encoded_payment_10                    0
encoded_payment_11                    0
encoded_payment_12                    0
encoded_payment_13                    0
encoded_payment_14                    0
encoded_payment_15                    0
encoded_payment_16                    0
encoded_payment_17                    0
encoded_payment_18                    0
encoded_payment_19                    0
encoded_payment_20                    0
encoded_payment_21                    0
encoded_payment_22                    0
encoded_payment_23                    0
encoded_payment_24                    0
encoded_loans_account_holder_type     0
encoded_loans_credit_status           0
encoded_loans_credit_type             0
encoded_loans_account_currency        0
dtype: int64

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()

In [16]:
scaler.fit(df)

StandardScaler()

In [17]:
df['encoded_payment_0'].value_counts()

0.0    1025356
3.0      44295
1.0      34494
2.0       2529
Name: encoded_payment_0, dtype: int64

In [18]:
df

,record_number,days_since_opened,days_since_confirmed,primary_term,final_term,days_till_primary_close,days_till_final_close,loans_credit_limit,loans_next_payment_summary,loans_outstanding_balance,...,encoded_payment_19,encoded_payment_20,encoded_payment_21,encoded_payment_22,encoded_payment_23,encoded_payment_24,encoded_loans_account_holder_type,encoded_loans_credit_status,encoded_loans_credit_type,encoded_loans_account_currency
0,7,10,8,12,10,13,5,11,2,3,...,1.0,2.0,0.0,1.0,3.0,4.0,1,3,4,1
1,5,15,6,7,6,9,1,5,6,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
2,1,15,17,8,5,9,1,6,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
3,11,7,2,11,13,14,8,14,3,5,...,3.0,4.0,3.0,3.0,3.0,4.0,1,2,4,1
4,12,14,9,8,11,6,13,5,6,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106669,19,1,5,8,11,2,6,18,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,5,1
1106670,10,5,8,4,3,5,7,18,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,5,1
1106671,3,8,7,13,0,4,9,3,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
1106672,4,10,4,16,9,6,13,3,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
1106673,12,1,10,10,13,10,8,8,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,2,3,1

In [19]:
df=scaler.transform(df)

In [20]:
df=pd.DataFrame(df)

In [21]:
df

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,-0.374119,0.098479,-0.048443,0.680017,0.376130,1.124071,-0.739017,0.219696,-0.266638,0.010869,...,-1.016867,-1.061997,-1.921948,-1.148410,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
1,-0.722181,0.968389,-0.467179,-0.266593,-0.499998,0.338955,-1.664528,-0.806859,2.939957,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
2,-1.418305,0.968389,1.835870,-0.077271,-0.719030,0.338955,-1.664528,-0.635766,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
3,0.322005,-0.423466,-1.304651,0.490695,1.033226,1.320350,-0.044884,0.732974,0.535011,3.130353,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,-1.618196,0.396398,-0.03311
4,0.496036,0.794407,0.160925,-0.077271,0.595162,-0.249883,1.112004,-0.806859,2.939957,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106669,1.714253,-1.467357,-0.676547,-0.077271,0.595162,-1.035000,-0.507640,1.417344,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,1.385453,-0.03311
1106670,0.147974,-0.771430,-0.048443,-0.834560,-1.157095,-0.446162,-0.276262,1.417344,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,1.385453,-0.03311
1106671,-1.070243,-0.249484,-0.257811,0.869339,-1.814191,-0.642441,0.186493,-1.149044,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
1106672,-0.896212,0.098479,-0.885915,1.437305,0.157098,-0.249883,1.112004,-1.149044,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
1106673,0.496036,-1.467357,0.370293,0.301373,1.033226,0.535234,-0.044884,-0.293581,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,-1.618196,-0.592657,-0.03311

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df, Y, test_size=0.33, random_state=42)

In [24]:

import xgboost as xgb
from sklearn.metrics import accuracy_score

In [25]:
# Create an XGBoost model
xgb_model = xgb.XGBClassifier(objective='binary:logistic',n_estimators=50)

# Train the model on the training data
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=50, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [26]:
# Make predictions on the test data
y_pred = xgb_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)    
print(f"Accuracy: {accuracy:.5f}")

Accuracy: 0.99986

In [27]:
data=pd.read_csv("test 2.csv")

In [28]:
data.drop("customer_id",axis=1,inplace=True)

In [29]:
data.drop(['firstname','lastname'],inplace=True,axis=1)

In [30]:
from sklearn.preprocessing import LabelEncoder

columns_to_convert = ['is_zero_loans_within_5_days', 'is_zero_loans_within_5_to_30_days', 'is_zero_loans_within_30_to_60_days','is_zero_loans_within_60_to_90_days','is_zero_loans_over_90_days','is_zero_utilization','is_zero_over_limit_count','is_zero_max_over_limit_count']  # Replace with the actual column names

label_encoder = LabelEncoder()

for column in columns_to_convert:
    data[column] = label_encoder.fit_transform(data[column])

In [31]:


# Iterate through columns and fill null values with the mode
for column in data.columns:
    mode_value = data[column].mode().values[0]  # Find the mode value
    data[column].fillna(mode_value, inplace=True)  # Fill null values with the mode

In [32]:
data

,record_number,days_since_opened,days_since_confirmed,primary_term,final_term,days_till_primary_close,days_till_final_close,loans_credit_limit,loans_next_payment_summary,loans_outstanding_balance,...,encoded_payment_19,encoded_payment_20,encoded_payment_21,encoded_payment_22,encoded_payment_23,encoded_payment_24,encoded_loans_account_holder_type,encoded_loans_credit_status,encoded_loans_credit_type,encoded_loans_account_currency
0,14,2,13,14,2,14,6,1,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
1,17,3,6,0,1,0,4,8,2,4,...,0.0,1.0,0.0,0.0,0.0,1.0,1,2,3,1
2,14,9,10,14,7,10,4,2,5,1,...,3.0,4.0,3.0,3.0,3.0,4.0,1,2,4,1
3,7,14,4,12,11,6,13,11,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
4,13,3,3,16,1,15,4,16,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474284,1,10,4,7,11,6,13,5,6,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,4,1
474285,8,3,11,7,3,11,12,13,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,3,5,1
474286,12,6,13,12,10,16,7,16,2,3,...,1.0,2.0,0.0,0.0,1.0,1.0,1,3,4,1
474287,16,2,16,0,7,10,8,8,2,3,...,3.0,4.0,3.0,3.0,3.0,4.0,1,2,3,1
474288,8,10,14,12,10,13,5,12,2,3,...,0.0,1.0,0.0,0.0,0.0,1.0,1,3,4,1

In [33]:
scaler.fit(data)

StandardScaler()

In [34]:
data=scaler.transform(data)

In [35]:
data=pd.DataFrame(data)

In [36]:
data

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,0.840890,-1.292370,0.994776,1.057356,-1.375135,1.317010,-0.510433,-1.490030,-0.265024,0.01245,...,0.564154,0.546026,0.530426,0.514180,0.497078,0.426866,-0.101226,0.517902,0.397779,-0.031463
1,1.361980,-1.118409,-0.469553,-1.593049,-1.594362,-1.426444,-0.973466,-0.292605,-0.265024,1.57538,...,-1.808737,-1.868283,-1.922556,-1.981843,-2.049994,-2.382916,-0.101226,-1.616905,-0.588108,-0.031463
2,0.840890,-0.074647,0.367206,1.057356,-0.278998,0.533166,-0.973466,-1.318969,2.146265,-3.11341,...,0.564154,0.546026,0.530426,0.514180,0.497078,0.426866,-0.101226,-1.616905,0.397779,-0.031463
3,-0.374986,0.795155,-0.887933,0.678727,0.597912,-0.250678,1.110183,0.220577,-0.265024,0.01245,...,0.564154,0.546026,0.530426,0.514180,0.497078,0.426866,-0.101226,0.517902,0.397779,-0.031463
4,0.667194,-1.118409,-1.097123,1.435986,-1.594362,1.512971,-0.973466,1.075880,-0.265024,0.01245,...,0.564154,0.546026,0.530426,0.514180,0.497078,0.426866,-0.101226,0.517902,-0.588108,-0.031463
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474284,-1.417166,0.099313,-0.887933,-0.267846,0.597912,-0.250678,1.110183,-0.805787,2.950028,0.01245,...,0.564154,0.546026,0.530426,0.514180,0.497078,0.426866,-0.101226,0.517902,0.397779,-0.031463
474285,-0.201290,-1.118409,0.576396,-0.267846,-1.155907,0.729127,0.878667,0.562698,-0.265024,0.01245,...,0.564154,0.546026,0.530426,0.514180,0.497078,0.426866,-0.101226,0.517902,1.383666,-0.031463
474286,0.493497,-0.596528,0.994776,0.678727,0.378684,1.708932,-0.278916,1.075880,-0.265024,0.01245,...,-1.017774,-1.063513,-1.922556,-1.981843,-1.200970,-2.382916,-0.101226,0.517902,0.397779,-0.031463
474287,1.188284,-1.292370,1.622345,-1.593049,-0.278998,0.533166,-0.047400,-0.292605,-0.265024,0.01245,...,0.564154,0.546026,0.530426,0.514180,0.497078,0.426866,-0.101226,-1.616905,-0.588108,-0.031463
474288,-0.201290,0.099313,1.203966,0.678727,0.378684,1.121049,-0.741950,0.391637,-0.265024,0.01245,...,-1.808737,-1.868283,-1.922556,-1.981843,-2.049994,-2.382916,-0.101226,0.517902,0.397779,-0.031463

In [37]:
d=xgb_model.predict(data)

In [38]:
# Column names
column_names = ['primary_close_flag', 'final_close_flag']

# Convert the array to a DataFrame
dt = pd.DataFrame(d, columns=column_names)

# Save the DataFrame to a CSV file with column names
dt.to_csv('output_rohit_20.csv', index=False)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel



# Initialize the Random Forest classifier
clf = RandomForestClassifier()

# Fit the classifier to data
clf.fit(X_train, y_train)

# Use feature importances for feature selection
sfm = SelectFromModel(clf, threshold=0.1)  
sfm.fit(X_train, y_train)

# Transform  data to keep only the selected features
X_train_selected = sfm.transform(X_train)

In [ ]:
X_test_selected = sfm.transform(X_test)

In [ ]:
# Initialize a new classifier (or use the existing one)
clf_selected = RandomForestClassifier(n_estimators=130,max_features='sqrt')

# Fit the classifier to the selected feature training data
clf_selected.fit(X_train_selected, y_train)

In [ ]:
# Make predictions on the test data with selected features
y_pred_selected = clf_selected.predict(X_test_selected)

# Calculate accuracy for the model with selected features
accuracy_selected = accuracy_score(y_test, y_pred_selected)
print("Accuracy with selected features:", accuracy_selected)

In [ ]:

from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

In [ ]:
# Train separate AdaBoost models for each label
adaboost_models = []
for label in y_train.columns:
    adaboost_model = AdaBoostClassifier(n_estimators=100, random_state=42)
    adaboost_model.fit(X_train, y_train[label])
    adaboost_models.append(adaboost_model)

# Make predictions for each label
y_pred = pd.DataFrame(columns=y_test.columns)
for i, adaboost_model in enumerate(adaboost_models):
    y_pred[y_test.columns[i]] = adaboost_model.predict(X_test)

# Calculate accuracy for each label
accuracies = []
for label in y_test.columns:
    accuracy = accuracy_score(y_test[label], y_pred[label])
    accuracies.append(accuracy)
    print(f"Accuracy for {label}: {accuracy:.4f}")

# Calculate average accuracy
average_accuracy = sum(accuracies) / len(accuracies)
print(f"Average Accuracy: {average_accuracy:.4f}")

In [ ]:

# Make predictions using the trained models
new_predictions = pd.DataFrame(columns=['1', '2'])  # Create a DataFrame to store predictions
for i, model in enumerate(adaboost_models):
    new_predictions[new_predictions.columns[i]] = model.predict(data)

In [ ]:
# Specify the output CSV file path
output_file = 'output_data_7.csv'

# Save DataFrame to a CSV file without including the header
new_predictions.to_csv(output_file, index=False, header=False, mode='a')  # mode='a' to append to the file

# Manually add the specific column names as the first row
custom_column_names = "'primary_close_flag', 'final_close_flag'"
with open(output_file, 'r+') as f:
    content = f.read()
    f.seek(0, 0)
    f.write(custom_column_names + '\n' + content)

print(f"DataFrame saved to {output_file} with manually added column names")

In [40]:
df

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,-0.374119,0.098479,-0.048443,0.680017,0.376130,1.124071,-0.739017,0.219696,-0.266638,0.010869,...,-1.016867,-1.061997,-1.921948,-1.148410,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
1,-0.722181,0.968389,-0.467179,-0.266593,-0.499998,0.338955,-1.664528,-0.806859,2.939957,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
2,-1.418305,0.968389,1.835870,-0.077271,-0.719030,0.338955,-1.664528,-0.635766,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
3,0.322005,-0.423466,-1.304651,0.490695,1.033226,1.320350,-0.044884,0.732974,0.535011,3.130353,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,-1.618196,0.396398,-0.03311
4,0.496036,0.794407,0.160925,-0.077271,0.595162,-0.249883,1.112004,-0.806859,2.939957,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106669,1.714253,-1.467357,-0.676547,-0.077271,0.595162,-1.035000,-0.507640,1.417344,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,1.385453,-0.03311
1106670,0.147974,-0.771430,-0.048443,-0.834560,-1.157095,-0.446162,-0.276262,1.417344,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,1.385453,-0.03311
1106671,-1.070243,-0.249484,-0.257811,0.869339,-1.814191,-0.642441,0.186493,-1.149044,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
1106672,-0.896212,0.098479,-0.885915,1.437305,0.157098,-0.249883,1.112004,-1.149044,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,0.515681,0.396398,-0.03311
1106673,0.496036,-1.467357,0.370293,0.301373,1.033226,0.535234,-0.044884,-0.293581,-0.266638,0.010869,...,0.564497,0.546656,0.530698,0.514913,0.497854,0.426774,-0.100315,-1.618196,-0.592657,-0.03311

In [41]:
Y

         primary_close_flag  final_close_flag
0                         0                 0
1                         0                 0
2                         0                 0
3                         0                 0
4                         0                 0
...                     ...               ...
1106669                   0                 0
1106670                   0                 0
1106671                   0                 0
1106672                   0                 0
1106673                   0                 0

[1106674 rows x 2 columns]

In [42]:
pip install transformers

Collecting transformers
  Downloading transformers-4.34.1-py3-none-any.whl (7.7 MB)
     ---------------------------------------- 7.7/7.7 MB 5.0 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.1 in c:\users\rohit\anaconda3\lib\site-packages (from transformers) (6.0)
Collecting huggingface-hub<1.0,>=0.16.4
  Downloading huggingface_hub-0.18.0-py3-none-any.whl (301 kB)
     -------------------------------------- 302.0/302.0 kB 4.7 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in c:\users\rohit\anaconda3\lib\site-packages (from transformers) (21.3)
Requirement already satisfied: numpy>=1.17 in c:\users\rohit\anaconda3\lib\site-packages (from transformers) (1.21.5)
Requirement already satisfied: regex!=2019.12.17 in c:\users\rohit\anaconda3\lib\site-packages (from transformers) (2022.7.9)
Requirement already satisfied: requests in c:\users\rohit\anaconda3\lib\site-packages (from transformers) (2.28.1)
Collecting tokenizers<0.15,>=0.14
  Downloading tokenizers-0.14.1-cp39-none-win_amd64.whl (2.2 MB)
     ---------------------------------------- 2.2/2.2 MB 5.2 MB/s eta 0:00:00
Collecting safetensors>=0.3.1
  Downloading safetensors-0.4.0-cp39-none-win_amd64.whl (277 kB)
     -------------------------------------- 277.2/277.2 kB 4.2 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in c:\users\rohit\anaconda3\lib\site-packages (from transformers) (4.64.1)
Requirement already satisfied: filelock in c:\users\rohit\anaconda3\lib\site-packages (from transformers) (3.6.0)
Collecting fsspec>=2023.5.0
  Downloading fsspec-2023.10.0-py3-none-any.whl (166 kB)
     -------------------------------------- 166.4/166.4 kB 5.0 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\rohit\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (4.7.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\rohit\anaconda3\lib\site-packages (from packaging>=20.0->transformers) (3.0.9)
Collecting huggingface-hub<1.0,>=0.16.4
  Downloading huggingface_hub-0.17.3-py3-none-any.whl (295 kB)
     -------------------------------------- 295.0/295.0 kB 6.2 MB/s eta 0:00:00
Requirement already satisfied: colorama in c:\users\rohit\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.5)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rohit\anaconda3\lib\site-packages (from requests->transformers) (2023.5.7)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\rohit\anaconda3\lib\site-packages (from requests->transformers) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\rohit\anaconda3\lib\site-packages (from requests->transformers) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rohit\anaconda3\lib\site-packages (from requests->transformers) (3.3)
Installing collected packages: safetensors, fsspec, huggingface-hub, tokenizers, transformers
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2022.7.1
    Uninstalling fsspec-2022.7.1:
      Successfully uninstalled fsspec-2022.7.1
Successfully installed fsspec-2023.10.0 huggingface-hub-0.17.3 safetensors-0.4.0 tokenizers-0.14.1 transformers-4.34.1
Note: you may need to restart the kernel to use updated packages.

In [44]:
from transformers import TFGPT2ForSequenceClassification, GPT2Tokenizer

model_name = "gpt2"  # You can choose a specific variant like "gpt2-medium"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = TFGPT2ForSequenceClassification.from_pretrained(model_name, num_labels=2)

Downloading model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFGPT2ForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFGPT2ForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [45]:
from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

inputs = tokenizer(df, return_tensors="pt", padding=True, truncation=True)

ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).